name: Build Kivy App to APK

on:
  push:
    branches: [ main ] # This triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The build process runs on an fresh Ubuntu environment

    steps:
      - uses: actions/checkout@v4 # Step 1: Check out your code from the repository
      
      - name: Build APK
        uses: digreatbrian/buildozer-action@v2 # Step 2: Use the specialized GitHub action for Buildozer
        with:
          python-version: 3.8 # Specify the desired Python version
          buildozer-cmd: buildozer -v android debug # The command to execute (build in debug mode with verbose output)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4 # Step 3: Upload the resulting APK file as a workflow artifact
        with:
          name: package # The name of the downloadable artifact
          path: ./bin/*.apk # The path where Buildozer places the generated APK file
